spring:
  # ?????
  datasource:
    url: jdbc:mysql://192.168.86.26:12306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=PST
    username: dev
    password: $%^s=pIlI$%TGT#$GR#$R$CFscfds
    driver-class-name: com.mysql.cj.jdbc.Driver

# ?????????
code-generator:
  parent: com.mbb.apicenter # ??
  author: moubenben # ????
  moduleName: apicenter # ????
  controllerName: controller # controller???
  serviceName: service #service???
  serviceImplName: service.impl # service?????
  entityName: entity # ????????
  mapperName: mapper # mapper??
  formatEntity: "%s" # entity???
  formatService: "%sService" # service??
  formatServiceImpl: "%sServiceImpl" # service?????
  enableSwagger: false # ????swagger
  date: "2023-10-27"
  codeDir: "/out"
  mapperXmlPath: "/out"
  tables: "element_path,element_owner"